export const DISEASE_DETAILS_REQUEST = 'DISEASE_DETAILS_REQUEST';
export const DISEASE_DETAILS_SUCCESS = 'DISEASE_DETAILS_SUCCESS';
export const DISEASE_DETAILS_FAIL = 'DISEASE_DETAILS_FAIL';

export const DISEASE_LIST_REQUEST = 'DISEASE_LIST_REQUEST';
export const DISEASE_LIST_SUCCESS = 'DISEASE_LIST_SUCCESS';
export const DISEASE_LIST_FAIL = 'DISEASE_LIST_FAIL';

export const DISEASE_DELETE_REQUEST = 'DISEASE_DELETE_REQUEST';
export const DISEASE_DELETE_SUCCESS = 'DISEASE_DELETE_SUCCESS';
export const DISEASE_DELETE_FAIL = 'DISEASE_DELETE_FAIL';

export const DISEASE_SAVE_REQUEST = 'DISEASE_SAVE_REQUEST';
export const DISEASE_SAVE_SUCCESS = 'DISEASE_SAVE_SUCCESS';
export const DISEASE_SAVE_FAIL = 'DISEASE_SAVE_FAIL'

export const DISEASE_ADD_REQUEST = 'DISEASE_ADD_REQUEST';
export const DISEASE_ADD_SUCCESS = 'DISEASE_ADD_SUCCESS';
export const DISEASE_ADD_FAIL = 'DISEASE_ADD_FAIL'

export const REMOVE_SELECTED_DISEASE = "REMOVE_SELECTED_DISEASE";