export const SYMPTOM_DETAILS_REQUEST = 'SYMPTOM_DETAILS_REQUEST';
export const SYMPTOM_DETAILS_SUCCESS = 'SYMPTOM_DETAILS_SUCCESS';
export const SYMPTOM_DETAILS_FAIL = 'SYMPTOM_DETAILS_FAIL';

export const SYMPTOM_LIST_REQUEST = 'SYMPTOM_LIST_REQUEST';
export const SYMPTOM_LIST_SUCCESS = 'SYMPTOM_LIST_SUCCESS';
export const SYMPTOM_LIST_FAIL = 'SYMPTOM_LIST_FAIL';

export const SYMPTOM_DELETE_REQUEST = 'SYMPTOM_DELETE_REQUEST';
export const SYMPTOM_DELETE_SUCCESS = 'SYMPTOM_DELETE_SUCCESS';
export const SYMPTOM_DELETE_FAIL = 'SYMPTOM_DELETE_FAIL';

export const SYMPTOM_SAVE_REQUEST = 'SYMPTOM_SAVE_REQUEST';
export const SYMPTOM_SAVE_SUCCESS = 'SYMPTOM_SAVE_SUCCESS';
export const SYMPTOM_SAVE_FAIL = 'SYMPTOM_SAVE_FAIL'

export const SYMPTOM_ADD_REQUEST = 'SYMPTOM_ADD_REQUEST';
export const SYMPTOM_ADD_SUCCESS = 'SYMPTOM_ADD_SUCCESS';
export const SYMPTOM_ADD_FAIL = 'SYMPTOM_ADD_FAIL'

export const REMOVE_SELECTED_SYMPTOM = "REMOVE_SELECTED_SYMPTOM";