export const PASSWORD_REQUIRED = 'Password is required!';
export const EMAIL_REQUIRED = 'Email is required!';
export const EMAIL_TYPE = 'Please enter valid form of email!';
export const PHONE_TYPE = 'Phone number is a 10 or 11 numeric string!';
export const PASSWORD_SECURITY_ERROR = 'Password requires that at least one digit, 1 owercase letter, 1 upercase letter, 1 special letter and between 6 and 32 in length';
export const FULLNAME_REQUIRED = 'Fullname is required!';
export const PHONE_NUMBER_REQUIRED = 'Phone number is required!';
export const ADMIN_ROLE = "ADMIN";
export const USER_ROLE = "USER";